---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  annotations:
  {{ if .Values.gitlab.app }}app.gitlab.com/app: {{ .Values.gitlab.app | quote }}{{ end }}
  {{ if .Values.gitlab.env }}app.gitlab.com/env: {{ .Values.gitlab.env | quote }}{{ end }}
  labels:
    app: search-engine
    component: ui
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    track: "{{ .Values.application.track }}"
    tier: "{{ .Values.application.tier }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: search-engine
      component: ui
      release: {{ .Release.Name }}
      track: "{{ .Values.application.track }}"
      tier: "{{ .Values.application.tier }}"
  template:
    metadata:
      annotations:
        checksum/application-secrets: "{{ .Values.application.secretChecksum }}"
        {{ if .Values.gitlab.app }}app.gitlab.com/app: {{ .Values.gitlab.app | quote }}{{ end }}
        {{ if .Values.gitlab.env }}app.gitlab.com/env: {{ .Values.gitlab.env | quote }}{{ end }}
      name: ui-pod
      labels:
        app: search-engine
        component: ui
        release: {{ .Release.Name }}
        track: "{{ .Values.application.track }}"
        tier: "{{ .Values.application.tier }}"
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: ui
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: ui
          protocol: TCP
        env:
        - name: GITLAB_ENVIRONMENT_NAME
          value: {{ .Values.gitlab.envName }}
        - name: GITLAB_ENVIRONMENT_URL
          value: {{ .Values.gitlab.envURL }}
        - name: MONGO
          value: {{ .Values.mongoHost | default (printf "%s-mongodb" .Release.Name) }}
        - name: MONGO_PORT
          value: {{ .Values.mongoPort | default "27017" | quote }}
        - name: MONGO_PASSWORD
          value: {{ .Values.mongoPort | default "mongo-root-password" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
