---
service:
  internalPort: 8000
  externalPort: 8000

image:
  repository: registry.gitlab.korzhenko.info/otus-ops/apps/search_engine_ui
  tag: latest

ingress:
  class: nginx

mongoHost:
mongoPort:
