---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  annotations:
  {{- if .Values.prometheus.metrics }}
    prometheus.io/scrape: "true"
    prometheus.io/port: "{{ .Values.service.internalPort }}"
  {{- end }}
  labels:
    app: {{ template "appname" . }}
    component:  {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ template "appname" . }}
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    tier: "{{ .Values.global.application.tier }}"
