---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "crawler.fullname" . }}
  annotations:
  {{- if .Values.service.annotations }}
  {{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
  {{- if .Values.prometheus.metrics }}
  prometheus.io/scrape: "true"
  prometheus.io/port: "{{ .Values.service.internalPort }}"
  {{- end }}
  labels:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.service.internalPort }}
  selector:
    app: search-engine
    component: crawler
    release: {{ .Release.Name }}
    tier: "{{ .Values.application.tier }}"
